/**
 * OD analysis pass over the iDRS extracts → docs/od-findings.md.
 * Editorial doc; every number in it is computed here from the raw extracts
 * via the same selectors the site uses (scripts/lib/od.ts). Pair with
 * scripts/build-od-data.ts (site data) and tests/data/od.test.ts
 * (golden-value assertions).
 *
 * Column conventions (audit A03):
 *  - "Elsewhere in survey area" = outside Durham and Toronto, INSIDE the
 *    surveyed area (TTS planning districts outside Durham/Toronto);
 *  - "Beyond survey area" = TTS code 998 (External) only;
 *  - shares of Durham-origin trips use the Durham-origin denominator, never
 *    the all-trips total.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  loadOdDataset,
  getTotalTrips,
  getInternalTrips,
  getInternalShare,
  getDurhamToTorontoTrips,
  getTorontoToDurhamTrips,
  getMunicipalityPairFlows,
  getMunicipalityOriginProfile,
  getMunicipalityDestinationProfile,
  getModeComposition,
  getModeContexts,
  getRegionTravelProfile,
  getLocalComposition,
  getComparable2022,
  MUNI_IDS,
  MUNI_NAMES,
  MODE_GROUP_ORDER,
  MODE_GROUP_LABEL,
  type ModeGroup,
} from "./lib/od.ts";

const ROOT = resolve(import.meta.dirname, "..");
const OUT = resolve(ROOT, "docs/od-findings.md");

const ds = loadOdDataset();
const fmt = (v: number) => Math.round(v).toLocaleString("en-CA");
const pct = (v: number, digits = 1) => `${(v * 100).toFixed(digits)}%`;

// Pre-2022 public-CSV series for the longitudinal checks (D metro comparisons).
const normalized = JSON.parse(
  readFileSync(resolve(ROOT, "data/processed/normalized.json"), "utf8"),
) as { records: { surveyYear: number; geographyId: string; domain: string; metric: string; category: string | null; direction: string | null; period: string | null; value: number | null }[] };
const durhamTrip = (year: number, metric: string): number =>
  normalized.records
    .filter((r) => r.surveyYear === year && r.geographyId === "durham" && r.domain === "trip" && r.metric === metric && r.direction === "residents" && r.period === "all_day")
    .reduce((s, r) => s + (r.value ?? 0), 0);

const lines: string[] = [];
const say = (s = "") => lines.push(s);

const total = getTotalTrips(ds);
const internal = getInternalTrips(ds);
const toToronto = getDurhamToTorontoTrips(ds);
const fromToronto = getTorontoToDurhamTrips(ds);
const profiles = new Map(MUNI_IDS.map((id) => [id, getMunicipalityOriginProfile(ds, id)]));
const destinationProfiles = new Map(MUNI_IDS.map((id) => [id, getMunicipalityDestinationProfile(ds, id)]));
const pairs = getMunicipalityPairFlows(ds).sort((a, b) => b.totalTwoWay - a.totalTwoWay);
const comparable = getComparable2022(ds);
const region = getRegionTravelProfile(ds);
const local = getLocalComposition(ds);
const durhamOriginTrips = MUNI_IDS.reduce((s, id) => s + profiles.get(id)!.originTrips, 0);

say("# OD findings — 2022 TTS origin–destination analysis");
say();
say(`Computed from the four authenticated iDRS extracts (\`data/raw/idrs/\`, query provenance in`);
say(`\`docs/idrs-data.md\`, authorization in \`docs/data-permissions.md\`). All figures are expanded`);
say(`weekday trips by members of Durham households, 2022 TTS. Generated by \`scripts/analyze-od.ts\` —`);
say(`re-run it rather than editing numbers by hand.`);
say();

// --------------------------------------------------------------- headline ---
say("## Headline checks");
say();
say(`| Quantity | Value |`);
say(`|---|---|`);
say(`| Total trips (Durham households) | ${fmt(total)} |`);
say(`| Internal (origin and destination in Durham) | ${fmt(internal)} (${pct(internal / total, 2)}) |`);
say(`| Durham → Toronto | ${fmt(toToronto)} (${pct(toToronto / total, 2)} of all trips) |`);
say(`| Toronto → Durham | ${fmt(fromToronto)} (${pct(fromToronto / total, 2)} of all trips) |`);
say(`| 2016-comparable 2022 trips (excl2016 = 0) | ${fmt(comparable.total)} |`);
say(`| 2022-comparable transit | ${fmt(comparable.groups.transit ?? 0)} (${pct((comparable.groups.transit ?? 0) / comparable.total, 2)}) |`);
const t2016 = durhamTrip(2016, "transit_local") + durhamTrip(2016, "go_rail") + durhamTrip(2016, "joint_go_transit");
const tot2016 = durhamTrip(2016, "total");
say(`| 2016 transit (public CSV) | ${fmt(t2016)} of ${fmt(tot2016)} (${pct(t2016 / tot2016, 2)}) — independently verified |`);
say();
say(`Reconciliation notes: OD grand total differs from the curated public-CSV total (1,440,149) by`);
say(`12 trips (query/category residue, ≈0.001%); the OD-by-mode extract is 9 trips short of the`);
say(`unidimensional matrix (mode-not-stated trips absent from it). These are documented, not forced.`);
say();

// ------------------------------------------------------------------ A ---
say("## A. Municipality OD matrix (expanded weekday trips)");
say();
say("Rows are Durham-municipality origins. Columns: the eight municipalities, Toronto (aggregated over its 16 planning districts), elsewhere in the surveyed area, and beyond it (TTS code 998).");
say();
const cols = ["From \\ To", ...MUNI_IDS.map((id) => MUNI_NAMES[id]!), "Toronto", "Elsewhere surveyed", "Beyond", "Origin total"];
say(`| ${cols.join(" | ")} |`);
say(`|${cols.map(() => "---|").join("")}`);
for (const id of MUNI_IDS) {
  const p = profiles.get(id)!;
  const cells = MUNI_IDS.map((d) => {
    const f = p.destinations.find((x) => x.destinationId === d);
    return f ? fmt(f.trips) : "0";
  });
  const tor = p.destinations.find((x) => x.destinationId === "toronto");
  const external = p.destinations.find((x) => x.destinationId === "external");
  const elsewhereSurveyed = p.otherExternal - (external?.trips ?? 0);
  say(`| ${MUNI_NAMES[id]!} | ${cells.join(" | ")} | ${fmt(tor?.trips ?? 0)} | ${fmt(elsewhereSurveyed)} | ${fmt(external?.trips ?? 0)} | ${fmt(p.originTrips)} |`);
}
say();
say(`Toronto cells are the aggregate over all 16 Toronto planning districts (audit A02: one PD alone is not "Toronto"). Each row reconciles: municipalities + Toronto + elsewhere + beyond = origin total.`);
say();

// ------------------------------------------------------------------ B/C/D ---
say("## B–D. Retention and orientation by municipality");
say();
say("| Municipality | Trips originating | Stay in same municipality | Somewhere in Durham | To Toronto | Elsewhere outside Durham |");
say("|---|---|---|---|---|---|");
for (const id of MUNI_IDS) {
  const p = profiles.get(id)!;
  say(
    `| ${MUNI_NAMES[id]!} | ${fmt(p.originTrips)} | ${pct(p.orbitShares.same)} | ${pct(p.orbitShares.same + p.orbitShares.durham)} | ${pct(p.orbitShares.toronto)} | ${pct(p.orbitShares.outside)} |`,
  );
}
say();
const mostSelfContained = [...profiles.values()].sort((a, b) => b.orbitShares.same - a.orbitShares.same)[0]!;
const mostToronto = [...profiles.values()].sort((a, b) => b.orbitShares.toronto - a.orbitShares.toronto)[0]!;
const leastToronto = [...profiles.values()].sort((a, b) => a.orbitShares.toronto - b.orbitShares.toronto)[0]!;
say(
  `- Most self-contained: **${MUNI_NAMES[mostSelfContained.id]!}** (${pct(mostSelfContained.orbitShares.same)} of its trips stay inside the municipality).`,
);
say(
  `- Most Toronto-oriented: **${MUNI_NAMES[mostToronto.id]!}** (${pct(mostToronto.orbitShares.toronto)} of trips); least: **${MUNI_NAMES[leastToronto.id]!}** (${pct(leastToronto.orbitShares.toronto)}).`,
);
say();

// ------------------------------------------------------------------ E ---
say("## E. Top external destinations (beyond Durham)");
say();
{
  const agg = new Map<string, { name: string; trips: number }>();
  for (const p of profiles.values()) {
    for (const f of p.destinations) {
      if (f.group !== "outside") continue;
      const key = f.destinationId;
      const cur = agg.get(key) ?? { name: f.destinationName, trips: 0 };
      cur.trips += f.trips;
      agg.set(key, cur);
    }
  }
  const top = [...agg.values()].sort((a, b) => b.trips - a.trips).slice(0, 10);
  say("| Destination | Trips from all Durham municipalities |");
  say("|---|---|");
  for (const t of top) say(`| ${t.name} | ${fmt(t.trips)} |`);
  say();
}

// ------------------------------------------------------------------ F ---
say("## F. Mode by destination context (disjoint)");
say();
{
  const contexts = new Map(getModeContexts(ds).map((c) => [c.key, c]));
  const rows: { label: string; key: string }[] = [
    { label: "Same municipality (origin = destination)", key: "sameMunicipality" },
    { label: "Another Durham municipality", key: "otherDurham" },
    { label: "To Toronto", key: "toToronto" },
    { label: "Elsewhere in survey area (excl. beyond)", key: "elsewhereSurveyArea" },
    { label: "Beyond the surveyed area (code 998)", key: "beyondSurveyArea" },
    { label: "— combined: anywhere in Durham (overlaps rows 1–2)", key: "allInternalDurham" },
  ];
  say("| Context | " + MODE_GROUP_ORDER.map((g) => MODE_GROUP_LABEL[g]!).join(" | ") + " | Trips |");
  say("|---|" + MODE_GROUP_ORDER.map(() => "---|").join("") + "---|");
  for (const r of rows) {
    const c = contexts.get(r.key)!;
    say(`| ${r.label} | ${MODE_GROUP_ORDER.map((g) => pct(c.groups[g]! / c.trips)).join(" | ")} | ${fmt(c.trips)} |`);
  }
  const disjointSum = rows.slice(0, 5).reduce((s, r) => s + contexts.get(r.key)!.trips, 0);
  say();
  say(`The five disjoint contexts sum to ${fmt(disjointSum)} versus ${fmt(durhamOriginTrips)} Durham-origin trips in the unidimensional matrix (9-trip mode-not-stated residue). "Elsewhere in survey area" and "beyond the surveyed area" are reported separately — never pooled silently (audit A03).`);
  say();

  // Walk/drive contrast across disjoint contexts (the "boundary" candidate).
  const same = contexts.get("sameMunicipality")!;
  const cross = contexts.get("otherDurham")!;
  const sh = (c: { groups: Record<ModeGroup, number>; trips: number }, g: ModeGroup) => c.groups[g]! / c.trips;
  say(`Drive/walk contrast: within the same municipality drive ${pct(sh(same, "drive"))} / walk ${pct(sh(same, "walk"))}; between Durham municipalities drive ${pct(sh(cross, "drive"))} / walk ${pct(sh(cross, "walk"))}.`);
  say();
}

// ------------------------------------------------------------------ G ---
say("## G. Directional asymmetry by municipal pair");
say();
say("| Pair | A → B | B → A | Two-way | Imbalance (abs) | Imbalance (share of two-way) |");
say("|---|---|---|---|---|---|");
for (const p of pairs.slice(0, 12)) {
  const asym = Math.abs(p.aToB - p.bToA);
  say(
    `| ${MUNI_NAMES[p.a]!} ↔ ${MUNI_NAMES[p.b]!} | ${fmt(p.aToB)} | ${fmt(p.bToA)} | ${fmt(p.totalTwoWay)} | ${fmt(asym)} | ${pct(asym / p.totalTwoWay)} |`,
  );
}
say();
say("(Top 12 two-way pairs by volume. Direction distinguishes outbound from return travel; it does not label home-based versus non-home-based journeys.)");
say();

// ------------------------------------------------------------------ H ---
say("## H. Network centrality (weighted degree)");
say();
{
  const degree = new Map<string, number>();
  for (const id of MUNI_IDS) degree.set(id, 0);
  for (const p of pairs) {
    degree.set(p.a, (degree.get(p.a) ?? 0) + p.totalTwoWay);
    degree.set(p.b, (degree.get(p.b) ?? 0) + p.totalTwoWay);
  }
  const ranked = [...degree.entries()].sort((a, b) => b[1] - a[1]);
  say("Internal two-way volume per municipality (sum of all its municipal pair flows):");
  say();
  for (const [id, v] of ranked) say(`- ${MUNI_NAMES[id]!}: ${fmt(v)}`);
  say();
  say("Explore-only: do not publish centrality as such; translate to “how connected each community is to its neighbours”.");
  say();
}

// ------------------------------------------------------------------ I ---
say("## I. Planning-district hotspots (internal Durham, PD → PD)");
say();
{
  const cells: { o: string; d: string; trips: number }[] = [];
  for (let i = 0; i < ds.matrix.rowNames.length; i++) {
    const o = ds.matrix.rowNames[i]!;
    if (!MUNI_IDS.some((id) => MUNI_NAMES[id] === o)) continue;
    for (let j = 0; j < ds.matrix.colNames.length; j++) {
      const d = ds.matrix.colNames[j]!;
      if (!MUNI_IDS.some((id) => MUNI_NAMES[id] === d)) continue;
      cells.push({ o, d, trips: ds.matrix.values[i]![j]! });
    }
  }
  cells.sort((a, b) => b.trips - a.trips);
  say("Top 15 PD→PD relationships inside Durham (these are the seeds of future zoom-in stories):");
  say();
  for (const c of cells.slice(0, 15)) say(`- ${c.o} → ${c.d}: ${fmt(c.trips)}`);
  say();
}

// ------------------------------------------------------------- composition ---
say("## J. What kind of local? (mutually exclusive composition of all Durham-household trips)");
say();
say(`| Group | Trips | Share of ${fmt(local.totalTrips)} |`);
say(`|---|---|---|`);
say(`| Both endpoints in the same municipality | ${fmt(local.sameMunicipality)} | ${pct(local.sameMunicipality / local.totalTrips)} |`);
say(`| Between Durham municipalities | ${fmt(local.betweenDurhamMunicipalities)} | ${pct(local.betweenDurhamMunicipalities / local.totalTrips)} |`);
say(`| At least one endpoint outside Durham | ${fmt(local.outsideInvolving)} | ${pct(local.outsideInvolving / local.totalTrips)} |`);
say();
say(`The last group includes trips entirely outside Durham made by Durham-household members. Same-municipality + between-municipalities = the ${pct(internal / total, 2)} internal share.`);
say();
const top3 = pairs.slice(0, 3);
const top3Sum = top3.reduce((s, p) => s + p.totalTwoWay, 0);
say(`Concentration: the top three municipal pairs (${top3.map((p) => `${MUNI_NAMES[p.a]!}–${MUNI_NAMES[p.b]!}`).join(", ")}) carry ${fmt(top3Sum)} two-way trips — ${pct(top3Sum / local.betweenDurhamMunicipalities)} of all intermunicipal Durham travel.`);
say();

// ------------------------------------------------------------------ findings ---
say("## Candidate findings (ranked internally — do not publish the ranking)");
say();

interface Finding {
  title: string;
  why: string;
  calc: string;
  viz: string;
  headline: string;
  caveats: string[];
  scores: { surprise: number; relevance: number; visual: number; robustness: number; accessibility: number };
}

const internalShare = getInternalShare(ds);
const elsewhereOutsideDurham = region.elsewhereSurveyArea + region.beyondSurveyArea;
const internalCtx = getModeComposition(ds, { origin: "durham", destination: "durham" });
const torontoCtx = getModeComposition(ds, { origin: "durham", destination: "toronto" });
const sh = (ctx: { trips: Record<ModeGroup, number>; total: number }, g: ModeGroup) => pct(ctx.trips[g]! / ctx.total);
const findings: Finding[] = [
  {
    title: "Durham is a region of local movement",
    why: "Counters the default “bedroom community” framing; reframes transportation conversation around the region's own network.",
    calc: `getInternalTrips() / getTotalTrips() = ${fmt(internal)} / ${fmt(total)} = ${pct(internalShare, 2)}`,
    viz: "Scroll-driven reveal: trips appear, Toronto looms, then the internal share fills the frame (79% number).",
    headline: "About four in five weekday trips made by Durham residents both begin and end within Durham Region.",
    caveats: [
      "Population scope: trips by members of Durham households, ages 5+ in 2022 (not comparable with pre-2022 trip counts).",
      "“Durham” = the eight area municipalities (TTS planning districts).",
    ],
    scores: { surprise: 5, relevance: 5, visual: 5, robustness: 5, accessibility: 5 },
  },
  {
    title: "The borders aren't where movement stops — strong inter-municipal corridors",
    why: "Shows Durham as one connected network, not eight isolated towns; supports regional (not local-by-local) service planning.",
    calc: `Two-way municipal pairs: Whitby↔Oshawa ${fmt(pairs[0]!.totalTwoWay)}, Oshawa↔Clarington ${fmt(pairs[1]!.totalTwoWay)}, Pickering↔Ajax ${fmt(pairs[2]!.totalTwoWay)} … top three = ${pct(top3Sum / local.betweenDurhamMunicipalities)} of intermunicipal travel`,
    viz: "Staged desire-line map: outlines → largest corridor → next → full network; width = √trips.",
    headline: "Durham's communities are tied together: tens of thousands of weekday trips cross each municipal border.",
    caveats: ["Desire lines show where trips begin and end, not routes used.", "Display threshold: only show flows above a chosen minimum to avoid hairlines."],
    scores: { surprise: 4, relevance: 5, visual: 5, robustness: 5, accessibility: 4 },
  },
  {
    title: "Where we're going changes how we get there",
    why: "The clearest mode-story: walking nearly vanishes and transit triples when the destination is Toronto instead of down the street.",
    calc: `Same-municipality vs Durham→Toronto mode shares (by-mode OD extract): drive ${sh(internalCtx, "drive")} → ${sh(torontoCtx, "drive")}, ride ${sh(internalCtx, "ride")} → ${sh(torontoCtx, "ride")}, walk ${sh(internalCtx, "walk")} → ${sh(torontoCtx, "walk")}, transit ${sh(internalCtx, "transit")} → ${sh(torontoCtx, "transit")}`,
    viz: "One morphing stacked bar between the two contexts (the visual centrepiece).",
    headline: "Trips to Toronto look nothing like trips across town — transit carries several times the share.",
    caveats: ["Mode-not-stated trips (9 overall) absent from the by-mode extract.", "Shares of trips, not persons.", "Association with the destination context, not a causal effect of crossing a boundary."],
    scores: { surprise: 4, relevance: 5, visual: 5, robustness: 5, accessibility: 4 },
  },
  {
    title: "Every municipality has its own travel orbit",
    why: "Personal/shareable: every reader lives in one of the eight orbits; invites self-identification (“what does Whitby look like?”).",
    calc: `Per-municipality origin profiles; e.g. ${MUNI_NAMES[mostSelfContained.id]!} keeps ${pct(mostSelfContained.orbitShares.same)} of its trips inside its own border; ${MUNI_NAMES[mostToronto.id]!} sends ${pct(mostToronto.orbitShares.toronto)} to Toronto.`,
    viz: "“Choose your community” selector → animated destination composition + top destinations.",
    headline: "Pick your community: each has its own travel orbit — and they are surprisingly different.",
    caveats: ["Origin-based only (where trips starting here go).", "Small external flows hidden from display below the stated threshold."],
    scores: { surprise: 3, relevance: 5, visual: 4, robustness: 5, accessibility: 5 },
  },
  {
    title: "Toronto is the single largest outside destination — bigger than everywhere else combined",
    why: `Corrects the earlier reversed claim: Durham-origin trips to Toronto (${fmt(toToronto)}, ${pct(toToronto / durhamOriginTrips, 2)} of Durham-origin trips) exceed those to ALL other destinations outside Durham combined (${fmt(elsewhereOutsideDurham)}, ${pct(elsewhereOutsideDurham / durhamOriginTrips, 2)}).`,
    calc: `Toronto ${fmt(toToronto)} vs elsewhere-outside-Durham ${fmt(elsewhereOutsideDurham)} (elsewhere surveyed ${fmt(region.elsewhereSurveyArea)} + beyond ${fmt(region.beyondSurveyArea)}), denominators = ${fmt(durhamOriginTrips)} Durham-origin trips`,
    viz: "Two-bar comparison inside the orbit chapter; the “outside” slice splits into Toronto vs everywhere else.",
    headline: "More Durham trips head to Toronto than to every other destination outside the region combined.",
    caveats: [
      "Shares use Durham-origin trips as denominator — not the all-trips total (the earlier version mixed the two and reversed the conclusion).",
      "Aggregates many small flows; “elsewhere” ranges from York Region to Peterborough and beyond the survey area.",
      "Trip-based, all purposes; not a commuting measure.",
    ],
    scores: { surprise: 4, relevance: 4, visual: 3, robustness: 5, accessibility: 4 },
  },
  {
    title: "Transit had not yet returned to its 2016 share",
    why: "The one clean longitudinal OD-adjacent finding; grounds the post-pandemic story in a like-for-like comparison.",
    calc: `2016: ${fmt(t2016)} / ${fmt(tot2016)} = ${pct(t2016 / tot2016, 2)}; 2022 comparable (excl2016 = 0): ${fmt(comparable.groups.transit ?? 0)} / ${fmt(comparable.total)} = ${pct((comparable.groups.transit ?? 0) / comparable.total, 2)}`,
    viz: "Two-bar comparable comparison inside the Long View chapter, clearly flagged as the comparable basis.",
    headline: "On a comparable survey basis, transit represented a smaller share of Durham trips in 2022 than in 2016 (3.9% vs 6.4%).",
    caveats: [
      "2022 reflects a post-pandemic travel environment; the TTS alone cannot say why.",
      "The data guide defines excl2016 values 0/1/2 (0 = comparable basis; 2 covers excluded non-commute walking); DMG's guidance is excl2016 = 0 for comparisons. Never present excl0 + excl1 as the full 2022 total.",
      "Never place full-basis 2022 mode shares on the historical line (walking capture changed).",
    ],
    scores: { surprise: 3, relevance: 4, visual: 3, robustness: 4, accessibility: 3 },
  },
];

const scoreOf = (f: Finding) =>
  f.scores.surprise + f.scores.relevance + f.scores.visual + f.scores.robustness + f.scores.accessibility;
const ranked = [...findings].sort((a, b) => scoreOf(b) - scoreOf(a));
ranked.forEach((f, i) => {
  say(`### ${i + 1}. ${f.title}`);
  say();
  say(`**Finding:** ${f.headline}`);
  say();
  say(`**Why it matters:** ${f.why}`);
  say();
  say(`**Exact calculation:** \`${f.calc}\``);
  say();
  say(`**Source:** 2022 TTS via DMG iDRS (Durham-household filter, expanded weekday trips)${f.title.includes("Transit") ? "; 2016 figure from the public 2022-era CSV pipeline (normalized.json)" : ""}.`);
  say();
  say(`**Potential visualization:** ${f.viz}`);
  say();
  say(`**Potential headline:** “${f.headline}”`);
  say();
  say("**Caveats:**");
  for (const c of f.caveats) say(`- ${c}`);
  say();
});

writeFileSync(OUT, lines.join("\n") + "\n");
console.log(`analyze-od: wrote docs/od-findings.md (${findings.length} candidate findings)`);
console.log(`analyze-od: internal ${pct(internalShare, 2)} · toToronto ${fmt(toToronto)} vs elsewhereOutside ${fmt(elsewhereOutsideDurham)} · top pair ${MUNI_NAMES[pairs[0]!.a]!}↔${MUNI_NAMES[pairs[0]!.b]!} ${fmt(pairs[0]!.totalTwoWay)}`);
